Repository hivehr/github-actions, pull requests merged in 2020-09, with the labels that each got.

#33 fix(document-routes): remove || symbol for or groups
  packages/document-routes/babel-plugin-express-routes/src/index.ts
Labels: bug, size/XS

#36 fix(workflows): globs are incorrect
  .github/workflows/chromatic.yml
  .github/workflows/document-routes.yml
  .github/workflows/get-jira-issue.yml
  .github/workflows/image-actions.yml
  .github/workflows/terraform-github-actions.yml
  .github/workflows/tflint.yml
  .github/workflows/transition-jira-issue.yml
  .github/workflows/update-pr.yml
  workflows/document-routes.yml
  workflows/get-jira-issue.yml
  workflows/image-actions.yml
  workflows/terraform-github-actions.yml
  workflows/tflint.yml
  workflows/transition-jira-issue.yml
  workflows/update-pr.yml
Labels: size/L

#37 test: update snapshots
  packages/document-routes/babel-plugin-express-routes/test/__snapshots__/permissions.test.ts.snap
Labels: size/XS
